# Merge CSV files

In [1]:
import os
from glob import glob
import pandas as pd

In [ ]:
csv_dir = r'D:\Data\Advan\dewey-downloads\neighborhood-patterns-us-home-panel-summary'

all_csv_files = glob(os.path.join(csv_dir, '*.csv.gz'))
all_dfs = []
for csv_file in all_csv_files:
    print(f"Reading {csv_file}...")
    df = pd.read_csv(csv_file, dtype={'placekey': str})
    all_dfs.append(df)
combined_df = pd.concat(all_dfs, ignore_index=True)
fname = os.path.join(csv_dir, 'combined_neighborhood_patterns_20251008.csv.gz')
combined_df.to_csv(fname, index=False, compression='gzip')

In [45]:
combined_df.query("ISO_COUNTRY_CODE == 'US' and YEAR == 2022").sample(10)['NUMBER_DEVICES_RESIDING']

11316938    137.0
13494105     91.0
21615744     63.0
11892781    176.0
898070       26.0
11315809    135.0
16481051    103.0
11218001     59.0
9200128     145.0
14986601     28.0
Name: NUMBER_DEVICES_RESIDING, dtype: float64

In [2]:
# ! pip install ipfn
import os
import glob
import json
from tqdm import tqdm
from natsort import natsorted
import pandas as pd

from datetime import datetime, timedelta

In [3]:
import numpy as np
import pandas as pd
from ipfn import ipfn
pd.set_option('display.max_columns', None)


m = [[40, 30, 20, 10], [35, 50, 100, 75], [30, 80, 70, 120], [20, 30, 40, 50]]
# m = [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

m = np.array(m)
xip = np.array([150, 300, 400, 150])
xpj = np.array([200, 300, 400, 100])

aggregates = [xip, xpj]
dimensions = [[0], [1]]

IPF = ipfn.ipfn(m, aggregates, dimensions, convergence_rate=1e-6)
m = IPF.iteration()
print(m)

[[ 64.55852549  46.23247384  35.38430991   3.82473358]
 [ 49.96791318  68.15934981 156.4985403   25.37417955]
 [ 56.72193658 144.42821667 145.0824759   53.76734831]
 [ 28.75162474  41.17995969  63.03467389  17.03373857]]


In [17]:
m.sum(axis=0)

array([200., 300., 400., 100.])

In [4]:
# df = pd.read_csv(r'G:\SafeGraph_monthly_patterns_2018-2022\2023\06\12\ADVAN\WP\patterns_weekly_000000000490.csv.gz')
df = pd.read_csv(r'H:\SafeGraph_monthly_patterns_2018-2022\2023\06\01\ADVAN\NP\neighborhood_patterns_000000000128.csv.gz')
df

area           area_type    origin_area_type  \
0     90091802003  Census Block Group  Census Block Group   
1     90034945003  Census Block Group  Census Block Group   
2    110010074041  Census Block Group  Census Block Group   
3    120559616021  Census Block Group  Census Block Group   
4    120860057042  Census Block Group  Census Block Group   
..            ...                 ...                 ...   
317  530730103032  Census Block Group  Census Block Group   
318  530399503001  Census Block Group  Census Block Group   
319   21000001003  Census Block Group  Census Block Group   
320   20200007034  Census Block Group  Census Block Group   
321  150030102012  Census Block Group  Census Block Group   

              date_range_start             date_range_end  \
0    2023-06-01T00:00:00-04:00  2023-07-01T00:00:00-04:00   
1    2023-06-01T00:00:00-04:00  2023-07-01T00:00:00-04:00   
2    2023-06-01T00:00:00-04:00  2023-07-01T00:00:00-04:00   
3    2023-06-01T00:00:00-04:00  2023-07-01T00:00:00-04:00   
4    2023-06-01T00:00:00-04:00  2023-07-01T00:00:00-04:00   
..                         ...                        ...   
317  2023-06-01T00:00:00-07:00  2023-07-01T00:00:00-07:00   
318  2023-06-01T00:00:00-07:00  2023-07-01T00:00:00-07:00   
319  2023-06-01T00:00:00-08:00  2023-07-01T00:00:00-08:00   
320  2023-06-01T00:00:00-08:00  2023-07-01T00:00:00-08:00   
321  2023-06-01T00:00:00-10:00  2023-07-01T00:00:00-10:00   

                                            day_counts  raw_stop_counts  \
0    {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             9215   
1    {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             6982   
2    {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             7097   
3    {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...            35894   
4    {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...            17697   
..                                                 ...              ...   
317  {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...            16270   
318  {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...            25671   
319  {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             9498   
320  {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             4864   
321  {"Monday":4,"Tuesday":4,"Wednesday":4,"Thursda...             6253   

     raw_device_counts                                       stops_by_day  \
0                 1650  [248,407,217,110,382,534,226,372,345,158,261,3...   
1                 1213  [337,308,204,82,357,320,268,363,477,288,100,61...   
2                 1887  [362,238,121,121,359,276,342,295,364,241,210,2...   
3                 7534  [845,1314,1619,1260,780,867,795,1318,1142,2220...   
4                 3527  [633,587,586,603,991,866,642,779,545,546,613,5...   
..                 ...                                                ...   
317               1500  [312,361,697,259,210,391,630,732,723,436,476,4...   
318                679  [1035,793,435,908,900,1622,475,550,746,892,455...   
319               1150  [30,73,75,23,175,45,0,180,414,542,962,954,1798...   
320                752  [194,220,192,306,209,128,177,205,264,197,139,2...   
321               1431  [114,194,271,190,176,127,213,257,295,282,184,2...   

                                    stops_by_each_hour  \
0    [0,0,0,0,0,0,0,14,0,0,0,22,0,0,43,21,55,0,11,2...   
1    [0,0,0,0,0,0,24,30,16,16,15,47,18,27,30,12,6,1...   
2    [0,0,0,0,19,37,26,31,31,37,31,18,11,29,0,17,0,...   
3    [16,0,0,0,0,12,6,28,25,112,34,59,57,54,58,76,2...   
4    [0,0,12,0,9,36,0,33,0,10,25,24,31,64,32,56,54,...   
..                                                 ...   
317  [36,7,0,0,0,0,0,11,0,10,19,15,0,13,21,0,0,34,2...   
318  [0,0,19,16,58,80,123,70,85,132,23,23,28,22,12,...   
319  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,10,0,0,0,0...   
320  [7,6,0,0,0,0,0,0,26,0,16,0,0,0,22,0,19,24,18,2...   
321  [0,0,0,0,0,0,0,11,0,21,0,0,0,0,24,11,0,0,18,0,...   

                        

In [21]:
len(df['stops_by_each_hour'][100]) / 23
len(df['stops_by_each_hour'][23])  / 24

80.16666666666667

In [5]:
# len(df['popularity_by_hour'][100])
df.columns

Index(['area', 'area_type', 'origin_area_type', 'date_range_start',
       'date_range_end', 'day_counts', 'raw_stop_counts', 'raw_device_counts',
       'stops_by_day', 'stops_by_each_hour', 'device_home_areas',
       'weekday_device_home_areas', 'weekend_device_home_areas',
       'breakfast_device_home_areas', 'lunch_device_home_areas',
       'afternoon_tea_device_home_areas', 'dinner_device_home_areas',
       'nightlife_device_home_areas', 'work_hours_device_home_areas',
       'work_behavior_device_home_areas', 'device_daytime_areas',
       'distance_from_home', 'distance_from_primary_daytime_location',
       'median_dwell', 'top_same_day_brand', 'top_same_month_brand',
       'popularity_by_each_hour', 'popularity_by_hour_monday',
       'popularity_by_hour_tuesday', 'popularity_by_hour_wednesday',
       'popularity_by_hour_thursday', 'popularity_by_hour_friday',
       'popularity_by_hour_saturday', 'popularity_by_hour_sunday',
       'device_type', 'iso_country_code', 're

In [158]:
df[['raw_visit_counts', 'normalized_visits_by_state_scaling']]

raw_visit_counts  normalized_visits_by_state_scaling
0                   NaN                                 NaN
1                   NaN                                 NaN
2                   NaN                                 NaN
3                   NaN                                 NaN
4                  23.0                               259.0
...                 ...                                 ...
29123             113.0                              1259.0
29124              45.0                               504.0
29125              46.0                               509.0
29126              17.0                               190.0
29127              45.0                               506.0

[29128 rows x 2 columns]

In [159]:
df['normalized_visits_by_state_scaling'] / df['raw_visit_counts']

0              NaN
1              NaN
2              NaN
3              NaN
4        11.260870
           ...    
29123    11.141593
29124    11.200000
29125    11.065217
29126    11.176471
29127    11.244444
Length: 29128, dtype: float64

In [160]:
df['normalized_visits_by_region_naics_visits'] / df['raw_visit_counts']

0             NaN
1             NaN
2             NaN
3             NaN
4        0.000061
           ...   
29123    0.000052
29124    0.000305
29125    0.000207
29126    0.017528
29127    0.000318
Length: 29128, dtype: float64

In [161]:
df.columns

Index(['placekey', 'parent_placekey', 'safegraph_brand_ids', 'location_name',
       'brands', 'store_id', 'top_category', 'sub_category', 'naics_code',
       'latitude', 'longitude', 'street_address', 'city', 'region',
       'postal_code', 'open_hours', 'category_tags', 'opened_on', 'closed_on',
       'tracking_closed_since', 'domains', 'geometry_type', 'polygon_wkt',
       'polygon_class', 'enclosed', 'phone_number', 'is_synthetic',
       'includes_parking_lot', 'iso_country_code', 'wkt_area_sq_meters',
       'date_range_start', 'date_range_end', 'raw_visit_counts',
       'raw_visitor_counts', 'visits_by_day', 'visits_by_each_hour', 'poi_cbg',
       'visitor_home_cbgs', 'visitor_home_aggregation', 'visitor_daytime_cbgs',
       'visitor_country_of_origin', 'distance_from_home', 'median_dwell',
       'bucketed_dwell_times', 'related_same_day_brand',
       'related_same_week_brand', 'device_type',
       'normalized_visits_by_state_scaling',
       'normalized_visits_by_regio

In [162]:
weekly_df = df

def get_all_files(root_dir, contains=[''], extions=['']):
    found_files = []
    for rt_dir, dirs, files in os.walk(root_dir):
        for ext in extions:
            ext = ext.lower()
            ext_len = len(ext)
            for file in files:
                file_ext = file[-(ext_len):]
                # print(file)
                file_ext = file_ext.lower()
                if file_ext == ext:
                    file_name = os.path.join(rt_dir, file)
                    found_files.append(file_name)
                    # continue                    
                
        for con in contains:
            con = con.lower()
            con_len = len(con)
            for file in files:
                if con in os.path.basename(file):
                    file_name = os.path.join(rt_dir, file)
                    found_files.append(file_name)
    return found_files


    
def split_to_county(df, saved_path, column_name='visitor_home_cbgs', file_suffix=''):
    if len(file_suffix) > 0:
            file_suffix = "_" +  file_suffix 
            
    df['county_code'] = df[column_name].str.zfill(12).str[:5]
    county_list = df['county_code'].unique()
    
    county_list = [c for c in county_list if c.isnumeric()]
    county_list = sorted(county_list) 
    print("   len of county_list:", len(county_list))

    df_row_cnt = len(df)
    removed_cnt = 0
    for idx, county in enumerate(county_list):  # cannot use tqdm in multiprocessing!     
        idxs = df['county_code'] == county
        county_df = df[idxs]
        
        basename = f'{county}_{column_name}{file_suffix}.csv'
        state_code = basename[:2]
        
        new_name = os.path.join(saved_path, state_code, county, basename)

        dirname = os.path.dirname(new_name)  
        os.makedirs(dirname, exist_ok=True)        
        
        county_df = county_df[[column_name, "placekey", "visits"]].sort_values(column_name)
        county_df.to_csv(new_name, index=False)
        removed_cnt += len(county_df)
        
        df = df[~idxs]



In [163]:

import sqlite3

saved_path = r'D:\Temp'
weekly_df = df

# clean data
weekly_df = weekly_df[~weekly_df['date_range_start'].isna()]
weekly_df = weekly_df[~weekly_df['date_range_end'].isna()] 
start_date = weekly_df['date_range_start'].min()[:10] # E.g.: 2018-01-15T00:00:00-09:00
end_date = weekly_df['date_range_end'].max()[:10]
 

# print(f"   Read {len(df_list)} files. Date range: {start_date} - {end_date}")
file_suffix = f"{start_date}_To_{end_date}"

def patterns_to_Sqlite(df, sqlite_name):
     
    conn = sqlite3.connect(sqlite_name)
    curs = conn.cursor()
    
    columns = ','.join(df.columns)
    columns.replace('placekey,parent_placekey', 'placekey PRIMARY KEY,parent_placekey')
    
    curs.execute('create table if not exists POI ' +
                f"({','.join(df.columns)})")
    df.to_sql('POI', conn, if_exists='replace', index=False)
    
    sql = f'CREATE INDEX placekey_idx ON POI(placekey);'    
    curs.execute(sql)
    
    conn.close

sqlite_saved_path = r'D:\Temp\weekly_patters_Sqlite'
 
basename = f'{file_suffix}_weekly_patterns_POI_only.db'

sqlite_name = os.path.join(sqlite_saved_path, basename)
sqlite_name
patterns_to_Sqlite(df.drop(columns=unfold_columns), sqlite_name)

In [119]:
# start_date = '2022-06-06'  
# end_date = datetime.strptime(start_date, '%Y-%m-%d') + timedelta(days=7)
# end_date = datetime.strftime(end_date, '%Y-%m-%d')




def unfold_df_columns(df, saved_path, file_suffix, columns=['visitor_home_cbgs', 'visitor_daytime_cbgs']):    
    for column in columns:
        pair_list = []
        print(f"   Creating edges for {len(df)} POIs...")
        df = df[~df[column].isna()]
        df.apply(unfold_row_dict, args=(pair_list, column), axis=1)
        pair_list_df = pd.DataFrame(pair_list)
        pair_list_df.columns = ["placekey", column, "visits"]

        print(f"   Created {len(pair_list_df)} edges.")

        print("   Splitting edges into county level...")
        os.makedirs(saved_path, exist_ok=True)
        split_to_county(df=pair_list_df, column_name=column, saved_path = saved_path, file_suffix=file_suffix)
        print("   Finish splitting edges.")

def unfold_row_dict(row, result_list, column_name='visitor_home_cbgs'):

    # if 'safegraph_place_id' in row.index:
    #     placekey = row["safegraph_place_id"]
    # print("column_name:", column_name)
    if 'placekey' in row.index:
        placekey = row["placekey"]
    try:     
        a_dict = json.loads(row[column_name])
        # print(a_dict)
        result_list += list(zip([placekey] * len(a_dict.keys()), a_dict.keys(), a_dict.values()))
    except Exception as e: 
        print("Error in  unfold_row_dict(): e, row[column_name]:", e, row[column_name])
        

# Unfold_columns    
unfold_columns=['visitor_home_cbgs', 'visitor_daytime_cbgs']
unfold_df_columns(df=weekly_df, saved_path=saved_path, file_suffix=file_suffix, columns=unfold_columns)                  

print("Done")
# # Save POI CSV without the split columns.
# POI_new_name = os.path.join(saved_path, "POI", f"POI_{file_suffix}.csv")
# os.makedirs(os.path.dirname(POI_new_name), exist_ok=True)
# print(f"   Saving POI files to: {POI_new_name}")
# # POI_drop_columns = ['visitor_home_cbgs', 'visitor_daytime_cbgs']
# POI_drop_columns = unfold_columns
# weekly_df.drop(columns=POI_drop_columns).to_csv(POI_new_name, index=False)

   Creating edges for 328799 POIs...
   Created 2168699 edges.
   Splitting edges into county level...
   len of county_list: 3218
   Finish splitting edges.
   Creating edges for 328799 POIs...
   Created 2148817 edges.
   Splitting edges into county level...
   len of county_list: 3216
   Finish splitting edges.
Done


In [72]:
file_suffix

'2022-06-06_To_2022-06-13'